bindAddress = ":50050"

[prometheus]
    url = "https://prometheus-k8s.openshift-monitoring:9091"
    bearerTokenFile = "/var/run/secrets/kubernetes.io/serviceaccount/token"
    [tlsConfig]
        insecureSkipVerify = true

[influxdb]
    address = "https://influxdb.alameda.svc.cluster.local:8086"
    username = "alameda"
    password = "alameda"
    retentionDuration = "30d"
    retentionShardDuration = "1d"

[log]
    setLogcallers = true
    outputLevel = "info" # debug, info, warn, error, fatal, none

[weavescope]
  url = "http://127.0.0.1:4040"