
bindAddress = ":50050"

[prometheus]
url = "https://prometheus-k8s.openshift-monitoring:9091"
bearerTokenFile = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  [prometheus.tlsConfig]
  insecureSkipVerify = true

[influxdb]
address = "https://influxdb.alameda.svc.cluster.local:8086"
username = "alameda"
password = "alameda"
insecureSkipVerify = true
retentionDuration = "150d"
retentionShardDuration = "1d"

[apis]
  [apis.metrics]
  source = "prometheus"
  target = "influxdb"

[log]
setLogcallers = true
outputLevel = "info" # debug, info, warn, error, fatal, none

[weavescope]
url = "http://127.0.0.1:4040"

[rabbitmq]
url = "amqp://admin:adminpass@rabbitmq.alameda.svc.cluster.local:5672"
  [rabbitmq.retry]
  publishTime = 3
  publishIntervalMs = 500

[keycode]
cliPath = "/opt/prophetstor/federatorai/bin/license_main"
refreshInterval = 180

[notifier]
  [notifier.keycode]
  enabled = true
  specs = "0 0 * * * *"
  eventInterval = "90,60,30,15,7,6,5,4,3,2,1,0,-1,-2,-3,-4,-5,-6,-7"
  eventLevel = "90:Info,15:Warn,0:Error"
